Сергей Гульчак a0_Done
SergeGoolchak/py111 pull request #2
Opened 2019-12-11 17:45 UTC by SergeGoolchak

на проверку

2019-12-11 17:56 UTC, nectostr requested changes

2019-12-11 17:56 UTC, nectostr commented on Tasks/a0_my_stack.py
> +	return some_list[ind]
А что если попросят peek индекса которого не существует?

2019-12-14 15:30 UTC, SergeGoolchak commented
s

2019-12-14 15:31 UTC, closed without merging

2019-12-18 08:06 UTC, nectostr commented on Tasks/a0_my_stack.py
>  	print(some_list)
Что это за куча принтов в clear?!
Они здесь явно лишние.

2019-12-18 08:06 UTC, nectostr commented on Tasks/a3_check_brackets.py
>  def check_brackets(brackets_row: str) -> bool:
Это не корректная проверка.
Пример: "( ))(" - это не корректная последовательность, у вас ответ True

2019-12-18 08:06 UTC, nectostr commented on Tasks/a3_check_brackets.py
> +	some_row = brackets_row
Зачем вам данная строчка? Почему не работать с параметром?

2019-12-18 08:06 UTC, nectostr commented on Tasks/a3_check_brackets.py
> +			return True
Предполагалось воспользоваться вашим собственным вариантом реализации стэка.

2019-12-18 08:06 UTC, nectostr commented on Tasks/a1_my_queue.py
> +		print(ind)
Лучше избавляться от таких print-ов

2019-12-18 08:06 UTC, nectostr commented on Tasks/a1_my_queue.py
>  	print(elem)
Роман оставил вам эти принты для примера, в реальном коде они - ошибка.